// ============================================================================
// Module:       build (build script)
// Description:  Embeds the Windows resources — the application icon and the
//               manifest that settles DPI awareness and the version lie.
//
// Dependencies: winresource (Windows only)
// ============================================================================

//! Embeds the Windows resources into the executable.
//!
//! Two things, and both are invisible until they are missing.
//!
//! ## The icon
//!
//! eframe sets a window icon at runtime, which covers the title bar and
//! the running window. Explorer, the taskbar, the Alt-Tab switcher and
//! the shortcut a user pins read an icon **resource** out of the `.exe`
//! itself, and a binary without one shows the generic blank-page icon in
//! every one of them.
//!
//! The icon comes from `assets/brand/icon.ico`, generated by
//! `cargo run --example brand_assets` from the single definition in
//! `src/brand.rs`. Do not hand-edit it.
//!
//! ## The manifest
//!
//! Windows lies to an application that does not have one, in two ways
//! that matter here:
//!
//! - **DPI.** Without a manifest declaring per-monitor awareness, Windows
//!   reports a virtualised resolution and then bitmap-scales the window.
//!   On a 150% display that is a blurry app, and on a machine with two
//!   monitors at different scalings it is a window that goes blurry when
//!   dragged between them. Every text label in a task manager is small,
//!   so this is not subtle.
//! - **The version.** `GetVersionEx` reports Windows 8 to an unmanifested
//!   app, forever, whatever it is actually running on. Nothing in this
//!   crate branches on the OS version today — [`crate::win::dwm`]
//!   deliberately probes instead — but an app that has been told it is on
//!   Windows 8 is one bad assumption away from a wrong answer, and the
//!   manifest costs nothing.
//!
//! `requestedExecutionLevel` is `asInvoker`, deliberately. A task manager
//! that demanded elevation would prompt on every launch, and most of what
//! it does needs no elevation at all — the process list, the graphs, the
//! service list and the startup list all work unprivileged. Elevation
//! buys the identity columns for other users' processes, and that is a
//! choice the user makes by running it as administrator, not one this
//! binary makes for them.
//!
//! Release builds fail if resources cannot be embedded; a distributable
//! binary without its manifest or Explorer icon is not a valid release.

fn main() {
    // Re-run only when the inputs change, rather than on every source
    // edit — this script is otherwise a fixed cost on every build.
    println!("cargo:rerun-if-changed=assets/brand/icon.ico");
    println!("cargo:rerun-if-changed=assets/rustaman.manifest");
    println!("cargo:rerun-if-changed=build.rs");

    #[cfg(windows)]
    embed_resources();
}

/// Embeds the icon and the manifest.
#[cfg(windows)]
fn embed_resources() {
    let mut resource = winresource::WindowsResource::new();

    if std::path::Path::new("assets/brand/icon.ico").exists() {
        resource.set_icon("assets/brand/icon.ico");
    } else {
        println!(
            "cargo:warning=assets/brand/icon.ico is missing; run \
             `cargo run --example brand_assets` to generate it. The binary \
             will show the generic blank-page icon in Explorer."
        );
    }

    if std::path::Path::new("assets/rustaman.manifest").exists() {
        resource.set_manifest_file("assets/rustaman.manifest");
    }

    // The version-info block Explorer's properties dialog reads. Taken
    // from Cargo.toml so it cannot disagree with the crate's own version.
    resource.set("ProductName", "Rustaman");
    // `FileDescription`, not the crate description — and this app is the
    // one place where getting that wrong is self-evident.
    //
    // The field is nominally a description, but every shipping Windows
    // binary puts a short product name in it ("Google Chrome"), because
    // it is what Task Manager and Explorer show as the program's name.
    // This one held the whole sentence from Cargo.toml, so Rustaman's own
    // row in its own process list read "A modern Windows task manager:
    // proces..." while every neighbouring row read a name. `win::identity`
    // resolves a display name from exactly this field.
    resource.set("FileDescription", "Rustaman");
    resource.set("Comments", env!("CARGO_PKG_DESCRIPTION"));
    resource.set("LegalCopyright", "MIT licensed");

    if let Err(error) = resource.compile() {
        if std::env::var("PROFILE").ok().as_deref() == Some("release") {
            eprintln!("could not embed required Windows release resources: {error}");
            std::process::exit(1);
        }
        println!("cargo:warning=could not embed Windows resources: {error}");
    }
}
